version: '3.3'
services:
  pgdb-on-esports:
    container_name: on_esports_pgdb
    image: postgres:16-alpine
    ports:
      - "50500:5432"
    environment:
      POSTGRES_USER: postgres
      DB_NAME: on_esports_db
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/on_esports_db
    volumes:
      - ./pgdb:/docker-entrypoint-initdb.d:ro
